#pragma once

/// @file image_formation.hpp
/// @brief Image formation engine for Sprint 10a total-power imaging.
///
/// Synthesises a realistic MultispectralImage from a set of celestial objects
/// in the field of view, applying per-band PSF rendering, photon counting,
/// sky background, Poisson noise, and Gaussian read noise.
///
/// ## Object-query interface
/// The engine is decoupled from the Universe via the narrow IObjectSource
/// abstract interface.  In production, wrap Universe in a thin adapter; in
/// tests, inject lightweight stubs directly.  The interface omits QueryFlags
/// because the formation engine always requests all object categories.
///
/// ## Flux → electron conversion
/// AB-magnitude flux (Jansky, from SNRCalculator::magnitude_to_flux_jy) is
/// converted to an electron count rate using the photon-counting formula:
///
///   S [e⁻/s] = f_ν [Jy] × 1e-26 × (Δλ/λ) × A [m²] × η / h
///
/// Δλ/λ is the fractional bandwidth (dimensionless), A is the total collecting
/// area, η is the area-weighted mean efficiency, and h = 6.626e-34 J·s.
/// The speed of light cancels when bandwidth is expressed as Δλ/λ.
///
/// ## Projection model
/// Objects are projected from (RA, Dec) to detector pixels via a gnomonic
/// (tangent-plane) projection centred on the pointing direction:
///
///   x_px = (width-1)/2  + x_arcsec / pixel_scale          (East → +x)
///   y_px = (height-1)/2 − y_arcsec / pixel_scale           (North → −y)
///
/// where pixel_scale = fov_arcsec / width_px.
///
/// ## RNG / reproducibility policy
/// Noise is generated by std::mt19937_64 seeded with ImageFormationParams::seed.
/// Same seed + same params → identical output (fully deterministic).  Noise is
/// recomputed from the full integration_time_s on every form() call; there is
/// no accumulated frame state between calls.

#include "imaging/image.hpp"
#include "imaging/multispectral_image.hpp"
#include "instruments/array_instrument.hpp"
#include "universe/celestial_object.hpp"
#include "core/types.hpp"

#include <string>
#include <vector>

namespace parallax::imaging
{

// ---------------------------------------------------------------------------
// IObjectSource — narrow query interface
// ---------------------------------------------------------------------------

/// @brief Abstract source of celestial objects for the image formation engine.
///
/// Production code wraps the Universe through this interface; test stubs
/// return hand-crafted object lists without requiring real catalog files.
class IObjectSource
{
public:
    IObjectSource()                                = default;
    virtual ~IObjectSource()                       = default;
    IObjectSource(const IObjectSource&)            = delete;
    IObjectSource& operator=(const IObjectSource&) = delete;

    /// @brief Fill @p results with objects inside the given sky cone.
    ///
    /// Implementations MUST clear @p results before populating it.
    ///
    /// @param ra_rad      Cone centre right ascension (radians, J2000).
    /// @param dec_rad     Cone centre declination (radians, J2000).
    /// @param radius_deg  Half-angle of the query cone (degrees).
    /// @param mag_limit   Faintest magnitude to include.
    /// @param results     Output buffer (cleared then filled by the implementation).
    virtual void query_fov(double                                   ra_rad,
                           double                                   dec_rad,
                           double                                   radius_deg,
                           float                                    mag_limit,
                           std::vector<universe::CelestialObject>&  results) const = 0;
};

// ---------------------------------------------------------------------------
// BandSpec
// ---------------------------------------------------------------------------

/// @brief Describes one active spectral band in an imaging request.
struct BandSpec
{
    std::string band_name{};                    ///< Human-readable label (e.g. "Visible").
    u32         band_index           = 0;       ///< Index matching the ArrayInstrument band list.
    f64         center_wavelength_nm = 550.0;   ///< Band centre wavelength (nm).
    f64         bandwidth_nm         = 100.0;   ///< Full band width (nm).
};

// ---------------------------------------------------------------------------
// ImageFormationParams
// ---------------------------------------------------------------------------

/// @brief All parameters required for a single form() call.
struct ImageFormationParams
{
    /// Pointing centre right ascension (radians, J2000).
    f64 ra_rad = 0.0;

    /// Pointing centre declination (radians, J2000).
    f64 dec_rad = 0.0;

    /// Full angular field of view along the x-axis (arcsec).
    /// Pixel scale = fov_arcsec / width_px.
    f64 fov_arcsec = 60.0;

    /// Detector width in pixels.
    u32 width_px = 256;

    /// Detector height in pixels.
    u32 height_px = 256;

    /// Active spectral bands to image (one output plane per entry).
    std::vector<BandSpec> bands;

    /// Total integration time (seconds).
    f64 integration_time_s = 1.0;

    /// Sky background electron rate (electrons per second per pixel).
    /// Rough guide: V-band 22 mag/arcsec² ≈ 10 e⁻/s/px for a ~1 m aperture.
    f64 sky_background_e_per_s_px = 10.0;

    /// Gaussian read noise (electrons RMS per pixel per exposure).
    f64 read_noise_electrons = 3.0;

    /// Faintest V-magnitude to query from the object source.
    float mag_limit = 20.0f;

    /// RNG seed for noise generation.
    /// Same seed + same params → identical output (see file docstring).
    u64 seed = 42u;
};

// ---------------------------------------------------------------------------
// ImageFormation
// ---------------------------------------------------------------------------

/// @brief Synthesises a noisy multispectral image from sources in the field.
///
/// All methods are static; this class carries no state.
class ImageFormation
{
public:
    /// @brief Produce a MultispectralImage for the given pointing and parameters.
    ///
    /// For each BandSpec the engine:
    ///  1. Creates a zero-initialised float image at the detector resolution.
    ///  2. Queries the object source for objects within the FOV (half-diagonal cone).
    ///  3. For each object: converts magnitude→Jy→electrons, projects via gnomonic
    ///     projection, and accumulates the PSF-convolved flux into the image plane.
    ///     Sub-resolution objects are rendered as point sources (10b scope for true
    ///     resolution via aperture synthesis).
    ///  4. Adds a flat sky background scaled by integration_time_s.
    ///  5. Per pixel: Poisson noise on (signal + background), then Gaussian read noise.
    ///
    /// @param params          Pointing, detector geometry, bands, noise config, RNG seed.
    /// @param instrument      The array instrument (aperture, stations, efficiency).
    /// @param object_source   Source of celestial objects for the FOV query.
    /// @return                MultispectralImage with one noisy band image per BandSpec.
    [[nodiscard]] static MultispectralImage form(
        const ImageFormationParams&          params,
        const instruments::ArrayInstrument&  instrument,
        const IObjectSource&                 object_source);
};

} // namespace parallax::imaging
