#pragma once

/// @file celestial_object.hpp
/// @brief CelestialObject — the universal representation of every astronomical object.
///
/// Uses std::variant instead of a raw C union (as suggested by the sprint doc) to
/// remain idiomatic C++20 and type-safe, while preserving "one of" semantics.

#include "universe/object_id.hpp"

#include <cstdint>
#include <string_view>
#include <variant>

namespace parallax::universe
{

// ---------------------------------------------------------------------------
// Type-specific sub-structs
// ---------------------------------------------------------------------------

/// @brief Extra data for real catalog stars and procedural stars.
struct StarData
{
    float         distance_pc        {0.0f};
    float         proper_motion_ra   {0.0f}; ///< mas/yr
    float         proper_motion_dec  {0.0f}; ///< mas/yr
    float         parallax_mas       {0.0f};
    std::uint32_t hip_id             {0};
    std::uint32_t hd_id              {0};
};

/// @brief Extra data for solar-system bodies.
struct SolarSystemData
{
    float distance_au              {0.0f};
    float phase_angle              {0.0f}; ///< degrees
    float apparent_diameter_arcsec {0.0f};
};

/// @brief Extra data for deep-sky objects (nebulae, clusters, etc.).
struct DsoData
{
    float         size_arcmin        {0.0f};
    float         surface_brightness {0.0f};
    std::uint32_t ngc_id             {0};
    std::uint32_t ic_id              {0};
};

/// @brief Extra data for external galaxies.
struct GalaxyData
{
    float redshift           {0.0f};
    float size_arcmin        {0.0f};
    float position_angle_deg {0.0f};
};

// ---------------------------------------------------------------------------
// CelestialObject
// ---------------------------------------------------------------------------

/// @brief Universal in-memory representation of any astronomical object.
///
/// Common fields hold identity, position (J2000 equatorial, radians) and
/// photometry.  Type-specific detail is stored in a @c std::variant — safer
/// and more idiomatic than the raw @c union suggested in the sprint document,
/// and still has "exactly one of" semantics.
struct CelestialObject
{
    // --- Identity ---
    ObjectType type {ObjectType::Unknown};
    u64        id   {0};

    // --- Position (J2000 equatorial, radians) ---
    double ra  {0.0};
    double dec {0.0};

    // --- Photometry ---
    float mag_v    {0.0f};
    float color_bv {0.0f};

    // --- Type-specific payload ---
    std::variant<std::monostate, StarData, SolarSystemData, DsoData, GalaxyData> data;

    // --- Helper predicates ---

    /// @brief True for objects from real astronomical catalogs.
    [[nodiscard]] constexpr bool is_real() const noexcept
    {
        return type == ObjectType::Star
            || type == ObjectType::SolarSystemBody
            || type == ObjectType::DeepSkyObject
            || type == ObjectType::Galaxy;
    }

    /// @brief True for objects generated by the procedural engine.
    [[nodiscard]] constexpr bool is_procedural() const noexcept
    {
        return type == ObjectType::ProceduralStar
            || type == ObjectType::ProceduralDso;
    }

    /// @brief Human-readable name of the object type.
    [[nodiscard]] constexpr std::string_view get_type_name() const noexcept
    {
        switch (type)
        {
            case ObjectType::Star:            return "Star";
            case ObjectType::SolarSystemBody: return "SolarSystemBody";
            case ObjectType::DeepSkyObject:   return "DeepSkyObject";
            case ObjectType::Galaxy:          return "Galaxy";
            case ObjectType::ProceduralStar:  return "ProceduralStar";
            case ObjectType::ProceduralDso:   return "ProceduralDso";
            default:                          return "Unknown";
        }
    }
};

} // namespace parallax::universe
